# Change these first
owner: hesingon # Your GitHub username
repo: revisit_watcher # Your GitHub repository name

# Add your sites here
sites:
  - name: Landing Page
    url: https://www.revisitvocab.com
  - name: Login Page
    url: https://beta.revisitvocab.com
  - name: Non-Existing Page
    url: https://broken3.revisitvocab.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /revisit_watcher
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Revisit Watcher
  introTitle: "**Revisit Watcher** monitors the up time of Revisit."
  introMessage: Notifies you when any website is down
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: telegram
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
